### ISSUE TITLE
Exception in thread RPCServer

### ISSUE THREAD

**Issue by bbjay** [tiagocoutinho/multivisor#21]
```
$ sudo supervisord -n -c /etc/supervisor/supervisord.conf
2019-03-05 00:10:25,099 CRIT Supervisor running as root (no user in config file)
2019-03-05 00:10:25,099 INFO Included extra file "/etc/supervisor/conf.d/sails.conf" during parsing
2019-03-05 00:10:25,103 INFO RPC interface 'supervisor' initialized
2019-03-05 00:10:25,104 INFO RPC interface 'multivisor' initialized
2019-03-05 00:10:25,104 CRIT Server 'inet_http_server' running without any HTTP authentication checking
Unlinking stale socket /var/run/supervisor.sock
2019-03-05 00:10:25,405 INFO RPC interface 'supervisor' initialized
2019-03-05 00:10:25,406 INFO RPC interface 'multivisor' initialized
2019-03-05 00:10:25,406 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-03-05 00:10:25,406 INFO supervisord started with pid 10501
No handlers could be found for logger "MVRPC"
2019-03-05 00:10:26,428 INFO spawned: 'sails' with pid 10510
2019-03-05 00:10:27,432 INFO success: sails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-03-05 00:18:14,846 INFO stopped: sails (exit status 0)
2019-03-05 00:19:23,586 INFO spawned: 'sails' with pid 11034
2019-03-05 00:19:25,028 INFO success: sails entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Exception in thread RPCServer:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/multivisor/rpc.py", line 198, in run_rpc_server
    del server
UnboundLocalError: local variable 'server' referenced before assignment

SystemError: (libev) error creating signal/async pipe: Too many open files
2019-03-04T23:48:10Z
Traceback (most recent call last):
  File "src/gevent/libev/corecext.pyx", line 1274, in gevent.libev.corecext._syserr_cb
  File "src/gevent/libev/corecext.pyx", line 542, in gevent.libev.corecext.loop._handle_syserr
  File "src/gevent/libev/corecext.pyx", line 550, in gevent.libev.corecext.loop.handle_error
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 485, in handle_error
  File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 507, in handle_system_error
error: cannot switch to a different thread
(libev) error creating signal/async pipe: Too many open files
Aborted
```

```
$ supervisord --version
3.3.1
```

```
$ sudo pip freeze | grep multi
multivisor==5.0.2
```

**Comment by tiagocoutinho** [comment]
@bbjay,
Thanks for reporting. Sorry for taking so long to give feedback.
It should be fixed by 52f4fb7.
Should become visible in next multivisor 5.0.3
